### ISSUE TITLE
Swift storage connection configuration is wrong

### ISSUE THREAD

**Issue by bmoqimi** [quay/config-tool#103]
Hi,
I have been trying to deploy Quay on an environment which has swift as storage option and the config validator fails even though quay itself is working fine with the backend storage after bypassing the validator. 
When looking at the source code here I noticed that the swift connection parameter isn't up to date with the upstream ncw/swift module: 
https://github.com/quay/config-tool/blob/673209c23cf0d21e3c1e3f957f161cccaba7da95/pkg/lib/shared/storage_validators.go#L451
Here you can see the tenant option is missing as per documentation :
https://github.com/ncw/swift/blob/master/README.md 

I have locally changed the config tool code and the connection works as expected when the tenant name is provided. 
I hope this info helps.

Thanks

**Comment by thomasmckay** [comment]
created jira issue to address
https://issues.redhat.com/browse/PROJQUAY-2069

**Comment by HammerMeetNail** [comment]
Jira issue closed earlier this year due to staleness.
