### ISSUE TITLE
config-tool fails on some secure passwords

### ISSUE THREAD

**Issue by eumel8** [quay/config-tool#81]
Quay: v3.4.0
config-tool v0.1.0
Red Hat Enterprise Linux release 8.3 (Ootpa)

Quay container won't start after upgrade to Quay v3.4.0 caused by some trouble with config-tool

```
$ config-tool validate -c /quay-registry/conf/stack/ --mode online
panic: runtime error: slice bounds out of range [1:0]
goroutine 24 [running]:
github.com/quay/config-tool/pkg/lib/fieldgroups/database.ValidateDatabaseConnection(0x7ffd55ca9661, 0x6, 0xc0004a9980, 0xc0001882d0, 0x0, 0x0, 0x0, 0x0)
        /remote-source/app/source/config-tool/pkg/lib/fieldgroups/database/database_validator.go:90 +0xca5
github.com/quay/config-tool/pkg/lib/fieldgroups/database.(*DatabaseFieldGroup).Validate(0xc000450fc0, 0x7ffd55ca9661, 0x6, 0xc0004a9980, 0xc0002a7848, 0x0, 0x0)
        /remote-source/app/source/config-tool/pkg/lib/fieldgroups/database/database_validator.go:55 +0x22a
github.com/quay/config-tool/commands.glob..func3.1(0xc0004a97a0, 0xc0004e2cd0, 0xc0004a9980, 0xc000451700, 0xc00040e222, 0xc00040eea0)
        /remote-source/app/source/config-tool/commands/validate.go:108 +0xd4
created by github.com/quay/config-tool/commands.glob..func3
        /remote-source/app/source/config-tool/commands/validate.go:93 +0x4eb
```
It seems DB_URI contains some problematic content in secure database password. The problematic sign is "?"
After removing this, config-tool works well. Of course I have to change the password in database backend ;-)
Thanks!

**Comment by eumel8** [comment]
Okay, the second complecated sign in the password string ("^") I struggled here: https://github.com/quay/config-tool/blob/f713d004cd2872c8a73fcc176c1f2055fd24a931/pkg/lib/fieldgroups/database/database_validator.go#L46

**Comment by thomasmckay** [comment]
Thanks for this report! Would you mind opening a ticker in our jira? If not, we can open one on your behalf.
https://issues.redhat.com/projects/PROJQUAY/issues

**Comment by eumel8** [comment]
@thomasmckay  sure: https://issues.redhat.com/browse/PROJQUAY-1585

thx!

**Comment by eumel8** [comment]
Feedback from RedHat support. Password must be urlencode in configuration settings:

origin:  `1234567?a^b`
urlencode: `1234567%3Fa%5Eb`
